const express = require('express');
const app = express();
app.listen('3000');
app.get('/', (req, res) => {
    res.send('Hello World!')
})
const database = require('./database');
const body = require('body-parser');
app.use(body.json());
app.use(body.urlencoded({ extended: false }));
const cors = require('cors');
app.use(cors({
    origin: 'http://localhost:4200',
    credentials: true
}));
const uuid = require('uuid');
const session = require('express-session');
var MySQLStore = require('express-mysql-session')(session);
var options = {
    port: 3306,
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'nogal'
};
var sessionStore = new MySQLStore(options);
app.use(session({
    secret: 'secret',
    genid: uuid.v4,
    resave: false,
    saveUninitialized: true,
    store: sessionStore,
    cookie: { secure: false }
}));
app.use(express.static('images'))
const login = require('./routes/login');
app.use('/login', login);
const profile = require('./routes/profile');
app.use('/profile', profile);
const allUsers = require('./routes/allUsers');
app.use('/allUsers', allUsers);
const addUsers = require('./routes/addUsers');
app.use('/addUsers', addUsers);
const getRoots = require('./routes/getRoots');
app.use('/getRoots', getRoots);
const getControls = require('./routes/getControl');
app.use('/getControls', getControls);
const deleteU = require('./routes/deleteU');
app.use('/deleteU', deleteU);
const updateUser = require('./routes/updateUser');
app.use('/updateUser', updateUser);
const getTypeOfRoot = require('./routes/getTypeOfRoot');
app.use('/getTypeOfRoot', getTypeOfRoot);
const addRoot = require('./routes/addRoot');
app.use('/addRoot', addRoot);
const deleteR = require('./routes/deleteR');
app.use('/deleteR', deleteR);
const updateR = require('./routes/updateR');
app.use('/updateR', updateR);
const addS = require('./routes/addS');
app.use('/addS', addS);
const allS = require('./routes/allS');
app.use('/allS', allS);
const delS = require('./routes/delS');
app.use('/delS', delS);
const updateS = require('./routes/updateS');
app.use('/updateS', updateS);
const allI = require('./routes/allI');
app.use('/allI', allI);
const addI = require('./routes/addI');
app.use('/addI', addI);
const delI = require('./routes/delI');
app.use('/delI', delI);
const goout = require('./routes/goout');
app.use('/goout', goout);
const allIm = require('./routes/allIm');
app.use('/allIm', allIm);
const updateI = require('./routes/updateI');
app.use('/updateI', updateI);
const addCa = require('./routes/addCa');
app.use('/addCa', addCa);
const allCa = require('./routes/allCa');
app.use('/allCa', allCa);
const delCa = require('./routes/delCa');
app.use('/delCa', delCa);
const updateCa = require('./routes/updateCa');
app.use('/updateCa', updateCa);
const allpayno = require('./routes/allpayno');
app.use('/allpayno', allpayno);
const addP = require('./routes/addP');
app.use('/addP', addP);
const delI0 = require('./routes/delI0');
app.use('/delI0', delI0);
const updateI0 = require('./routes/updateI0');
app.use('/updateI0', updateI0);
const addSC = require('./routes/addSC');
app.use('/addSC', addSC);
const allCustomer = require('./routes/allCustomer');
app.use('/allCustomer', allCustomer);
const delSC = require('./routes/delSC');
app.use('/delSC', delSC);
const updateSC = require('./routes/updateSC');
app.use('/updateSC', updateSC);
const addPay = require('./routes/addPay');
app.use('/addPay', addPay);
const getItemBooked = require('./routes/getItemBooked');
app.use('/getItemBooked', getItemBooked);
const closeItemD = require('./routes/closeItemD');
app.use('/closeItemD', closeItemD);
const addRequestto = require('./routes/addRequestto');
app.use('/addRequestto', addRequestto);
const allRequest = require('./routes/allRequestto');
app.use('/allRequest', allRequest);
const delRequestto = require('./routes/delRequestto');
app.use('/delRequestto', delRequestto);
const updateRequestto = require('./routes/updateRequestto');
app.use('/updateRequestto', updateRequestto);
const addRequesttoRF = require('./routes/addRequesttoRF');
app.use('/addRequesttoRF', addRequesttoRF);
const allRequestRF = require('./routes/allRequestRF');
app.use('/allRequestRF', allRequestRF);
const delRequesttoRF = require('./routes/delRequesttoRF');
app.use('/delRequesttoRF', delRequesttoRF);
const updateRequesttoRF = require('./routes/updateRequesttoRF');
app.use('/updateRequesttoRF', updateRequesttoRF);
const allRequestRFAns = require('./routes/allRequestRFAns');
app.use('/allRequestRFAns', allRequestRFAns);
const accept = require('./routes/acceptIam');
app.use('/accept', accept);
const acceptNo = require('./routes/acceptNoIam');
app.use('/acceptNo', acceptNo);
const allRequestRFAns00 = require('./routes/allRequestRFAns00');
app.use('/allRequestRFAns00', allRequestRFAns00);
const acceptHH = require('./routes/acceptHH');
app.use('/acceptHH', acceptHH);
const acceptNoHH = require('./routes/acceptNoHH');
app.use('/acceptNoHH', acceptNoHH);
const addPayOrder = require('./routes/addPayOrder');
app.use('/addPayOrder', addPayOrder);
const search = require('./routes/search');
app.use('/search', search);
const searchPay = require('./routes/searchPay');
app.use('/searchPay', searchPay);
const searchPay0 = require('./routes/searchPay0');
app.use('/searchPay0', searchPay0);
const searchPay00 = require('./routes/searchPay00');
app.use('/searchPay00', searchPay00);
const putMoney = require('./routes/putMoney');
app.use('/putMoney', putMoney);
const searchPay000 = require('./routes/searchPay000');
app.use('/searchPay000', searchPay000);
const allCa0 = require('./routes/allCa0');
app.use('/allCa0', allCa0);
const addIF = require('./routes/addIF');
app.use('/addIF', addIF);
const allSC0 = require('./routes/allSC0');
app.use('/allSC0', allSC0);
const addSCN = require('./routes/addSCN');
app.use('/addSCN', addSCN);
const delSC0 = require('./routes/delSC0');
app.use('/delSC0', delSC0);
const updateSC0 = require('./routes/updateSC0');
app.use('/updateSC0', updateSC0);
const addSCN0 = require('./routes/addSCN0');
app.use('/addSCN0', addSCN0);
const deleteImage = require('./routes/deleteImage');
app.use('/deleteImage', deleteImage);
const addSF = require('./routes/addSF');
app.use('/addSF', addSF);
const allCaNot = require('./routes/allCaNot');
app.use('/allCaNot', allCaNot);
const allCustomerP = require('./routes/allCustomerP');
app.use('/allCustomerP', allCustomerP);
const addS0CB = require('./routes/addS0CB');
app.use('/addS0CB', addS0CB);
const allCustomerP0 = require('./routes/allCustomerP0');
app.use('/allCustomerP0', allCustomerP0);
const updateSCR = require('./routes/updateSCR');
app.use('/updateSCR', updateSCR);
const allID = require('./routes/allID');
app.use('/allID', allID);
const addSCN0s = require('./routes/addSCN0s');
app.use('/addSCN0s', addSCN0s);
const allSC0s = require('./routes/allSC0s');
app.use('/allSC0s', allSC0s);
const addSCNs = require('./routes/addSCNs');
app.use('/addSCNs', addSCNs);
const delSC0s = require('./routes/delSC0s');
app.use('/delSC0s', delSC0s);
const updateSC0s = require('./routes/updateSC0s');
app.use('/updateSC0s', updateSC0s);
const getItemBooked000 = require('./routes/getItemBooked000');
app.use('/getItemBooked000', getItemBooked000);
const updateSC0sB = require('./routes/updateSC0sB');
app.use('/updateSC0sB', updateSC0sB);
const allSC0sB = require('./routes/allSC0sB');
app.use('/allSC0sB', allSC0sB);
const delSC0sB = require('./routes/delSC0sB');
app.use('/delSC0sB', delSC0sB);
const addSCNsB = require('./routes/addSCNsB');
app.use('/addSCNsB', addSCNsB);
const addSCN0sB = require('./routes/addSCN0sB');
app.use('/addSCN0sB', addSCN0sB);
const getItemBooked000B = require('./routes/getItemBooked000B');
app.use('/getItemBooked000B', getItemBooked000B);
const updateSC0A = require('./routes/updateSC0A');
app.use('/updateSC0A', updateSC0A);
const updateSCR0 = require('./routes/updateSCR0');
app.use('/updateSCR0', updateSCR0);
const delSC0F = require('./routes/delSC0F');
app.use('/delSC0F', delSC0F);
const insertSC0AOrder = require('./routes/insertSC0AOrder');
app.use('/insertSC0AOrder', insertSC0AOrder);
const allItembooked = require('./routes/allItembooked');
app.use('/allItembooked', allItembooked);
const allID01 = require('./routes/allID01');
app.use('/allID01', allID01);
const allIm0 = require('./routes/allIm0');
app.use('/allIm0', allIm0);
const delAll = require('./routes/delAll');
app.use('/delAll', delAll);
const orderto = require('./routes/orderto');
app.use('/orderto', orderto);
const allCustomerNot = require('./routes/allCustomerNot');
app.use('/allCustomerNot', allCustomerNot);
const ordertore = require('./routes/ordertore');
app.use('/ordertore', ordertore);
const addSCOffer = require('./routes/addSCOffer');
app.use('/addSCOffer', addSCOffer);
const allCustomerOffer = require('./routes/allCustomerOffer');
app.use('/allCustomerOffer', allCustomerOffer);
const allCustomerPOffer = require('./routes/allCustomerPOffer');
app.use('/allCustomerPOffer', allCustomerPOffer);
const allCustomerP0Offer = require('./routes/allCustomerP0Offer');
app.use('/allCustomerP0Offer', allCustomerP0Offer);
const updateSC0AOffer = require('./routes/updateSC0AOffer');
app.use('/updateSC0AOffer', updateSC0AOffer);
const addS0CBOffer = require('./routes/addS0CBOffer');
app.use('/addS0CBOffer', addS0CBOffer);
const updateSCR0Offer = require('./routes/updateSCR0Offer');
app.use('/updateSCR0Offer', updateSCR0Offer);
const delSC0Offer = require('./routes/delSC0Offer');
app.use('/delSC0Offer', delSC0Offer);
const delAllOffer = require('./routes/delAllOffer');
app.use('/delAllOffer', delAllOffer);
const toquotion = require('./routes/toquotion');
app.use('/toquotion', toquotion);
const getPayments = require('./routes/getPayments');
app.use('/getPayments', getPayments);
const returnback = require('./routes/returnback');
app.use('/returnback', returnback);
const allReturn = require('./routes/allReturn');
app.use('/allReturn', allReturn);
const allIDReturn = require('./routes/allIDReturn');
app.use('/allIDReturn', allIDReturn);
const allIBD = require('./routes/allIBD');
app.use('/allIBD', allIBD);
const allIBDP = require('./routes/allIBDP');
app.use('/allIBDP', allIBDP);
const addSCNAnother = require('./routes/addSCNAnother');
app.use('/addSCNAnother', addSCNAnother);
const allSC0Visit = require('./routes/allSC0Visit');
app.use('/allSC0Visit', allSC0Visit);
const allpaynoPay = require('./routes/allpaynoPay');
app.use('/allpaynoPay', allpaynoPay);
const allIB = require('./routes/allIB');
app.use('/allIB', allIB);
const allemployees = require('./routes/allemployees');
app.use('/allemployees', allemployees);
const addIAnother = require('./routes/addIAnother');
app.use('/addIAnother', addIAnother);
const allImAnother = require('./routes/allImAnother');
app.use('/allImAnother', allImAnother);
const deleteImageAnother = require('./routes/deleteImageAnother');
app.use('/deleteImageAnother', deleteImageAnother);
const getControlsTypeEmployee = require('./routes/getControlsTypeEmployee');
app.use('/getControlsTypeEmployee', getControlsTypeEmployee);
const addEmployee = require('./routes/addEmployee');
app.use('/addEmployee', addEmployee);
const allAttend = require('./routes/allAttend');
app.use('/allAttend', allAttend);
const addAtten = require('./routes/addAtten');
app.use('/addAtten', addAtten);
const updateEmployee = require('./routes/updateEmployee');
app.use('/updateEmployee', updateEmployee);
const delUEmployee = require('./routes/delUEmployee');
app.use('/delUEmployee', delUEmployee);
const allAttendSalary = require('./routes/allAttendSalary');
app.use('/allAttendSalary', allAttendSalary);
const addAttenSalary = require('./routes/addAttenSalary');
app.use('/addAttenSalary', addAttenSalary);
const getItemBooked000BDate = require('./routes/getItemBooked000BDate');
app.use('/getItemBooked000BDate', getItemBooked000BDate);
const allpaymentCustomer = require('./routes/allpaymentCustomer');
app.use('/allpaymentCustomer', allpaymentCustomer);
const allpaymentCustomerDate = require('./routes/allpaymentCustomerDate');
app.use('/allpaymentCustomerDate', allpaymentCustomerDate);